language: java
jdk:
  - openjdk8

branches: # (1)
  only:
    - master

# Travis CI 서버의 Home
cache: # (2)
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications: # (4)
  email:
    recipients:
      - leehyeonggyunhg@gmail.com